# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_dance(object):
    def setupUi(self, form_dance):
        form_dance.setObjectName("form_dance")
        form_dance.resize(361, 280)
        font = QtGui.QFont()
        font.setFamily("Arial")
        form_dance.setFont(font)
        form_dance.setStyleSheet("QWidget{\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"QAbstractButton{\n"
"border-style:none;\n"
"border-radius:0px;\n"
"padding:5px;\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #858585,stop:1 #383838);\n"
"}\n"
"QAbstractButton:hover{\n"
"color:#000000;\n"
"background-color:#008aff;\n"
"}\n"
"QAbstractButton:pressed{\n"
"color:#DCDCDC;\n"
"border-style:solid;\n"
"border-width:0px 0px 0px 4px;\n"
"padding:4px 4px 4px 2px;\n"
"border-color:#008aff;\n"
"background-color:#444444;\n"
"}\n"
"\n"
"QLabel{\n"
"color:#DCDCDC;\n"
"\n"
"\n"
"}\n"
"QLabel:focus{\n"
"border:1px solid #00BB9E;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#484848;\n"
"selection-color:#DCDCDC;\n"
"}\n"
"QLineEdit:focus,QLineEdit:hover{\n"
"border:1px solid #242424;\n"
"}\n"
"QLineEdit{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#484848;\n"
"selection-color:#DCDCDC;\n"
"}\n"
"\n"
"QLineEdit:focus,QLineEdit:hover{\n"
"border:1px solid #242424;\n"
"}\n"
"QLineEdit{\n"
"lineedit-password-character:9679;\n"
"}\n"
"font: 10pt \"Arial\";")
        self.button_dance_turn_around = QtWidgets.QPushButton(form_dance)
        self.button_dance_turn_around.setGeometry(QtCore.QRect(20, 240, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_dance_turn_around.setFont(font)
        self.button_dance_turn_around.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Arial\";")
        self.button_dance_turn_around.setObjectName("button_dance_turn_around")
        self.button_dance_dancing = QtWidgets.QPushButton(form_dance)
        self.button_dance_dancing.setGeometry(QtCore.QRect(260, 240, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_dance_dancing.setFont(font)
        self.button_dance_dancing.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial\";")
        self.button_dance_dancing.setObjectName("button_dance_dancing")
        self.button_dance_push_up = QtWidgets.QPushButton(form_dance)
        self.button_dance_push_up.setGeometry(QtCore.QRect(140, 100, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_dance_push_up.setFont(font)
        self.button_dance_push_up.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Arial\";")
        self.button_dance_push_up.setObjectName("button_dance_push_up")
        self.button_dance_stretch_self = QtWidgets.QPushButton(form_dance)
        self.button_dance_stretch_self.setGeometry(QtCore.QRect(260, 100, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_dance_stretch_self.setFont(font)
        self.button_dance_stretch_self.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Arial\";")
        self.button_dance_stretch_self.setObjectName("button_dance_stretch_self")
        self.button_dance_say_hello = QtWidgets.QPushButton(form_dance)
        self.button_dance_say_hello.setGeometry(QtCore.QRect(20, 100, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_dance_say_hello.setFont(font)
        self.button_dance_say_hello.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_dance_say_hello.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_dance_say_hello.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(137, 235, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Arial\";")
        self.button_dance_say_hello.setObjectName("button_dance_say_hello")
        self.button_dance_sit_down = QtWidgets.QPushButton(form_dance)
        self.button_dance_sit_down.setGeometry(QtCore.QRect(140, 240, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.button_dance_sit_down.setFont(font)
        self.button_dance_sit_down.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.button_dance_sit_down.setObjectName("button_dance_sit_down")
        self.button_dance_picture_1 = QtWidgets.QPushButton(form_dance)
        self.button_dance_picture_1.setGeometry(QtCore.QRect(20, 10, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.button_dance_picture_1.setFont(font)
        self.button_dance_picture_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_dance_picture_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_dance_picture_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(137, 235, 255);\n"
"color: rgb(0, 0, 0);")
        self.button_dance_picture_1.setText("")
        self.button_dance_picture_1.setObjectName("button_dance_picture_1")
        self.button_dance_picture_2 = QtWidgets.QPushButton(form_dance)
        self.button_dance_picture_2.setGeometry(QtCore.QRect(140, 11, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.button_dance_picture_2.setFont(font)
        self.button_dance_picture_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_dance_picture_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_dance_picture_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(137, 235, 255);\n"
"color: rgb(0, 0, 0);")
        self.button_dance_picture_2.setText("")
        self.button_dance_picture_2.setObjectName("button_dance_picture_2")
        self.button_dance_picture_3 = QtWidgets.QPushButton(form_dance)
        self.button_dance_picture_3.setGeometry(QtCore.QRect(260, 10, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.button_dance_picture_3.setFont(font)
        self.button_dance_picture_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_dance_picture_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_dance_picture_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(137, 235, 255);\n"
"color: rgb(0, 0, 0);")
        self.button_dance_picture_3.setText("")
        self.button_dance_picture_3.setObjectName("button_dance_picture_3")
        self.button_dance_picture_4 = QtWidgets.QPushButton(form_dance)
        self.button_dance_picture_4.setGeometry(QtCore.QRect(20, 150, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.button_dance_picture_4.setFont(font)
        self.button_dance_picture_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_dance_picture_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_dance_picture_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(137, 235, 255);\n"
"color: rgb(0, 0, 0);")
        self.button_dance_picture_4.setText("")
        self.button_dance_picture_4.setObjectName("button_dance_picture_4")
        self.button_dance_picture_5 = QtWidgets.QPushButton(form_dance)
        self.button_dance_picture_5.setGeometry(QtCore.QRect(140, 150, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.button_dance_picture_5.setFont(font)
        self.button_dance_picture_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_dance_picture_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_dance_picture_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(137, 235, 255);\n"
"color: rgb(0, 0, 0);")
        self.button_dance_picture_5.setText("")
        self.button_dance_picture_5.setObjectName("button_dance_picture_5")
        self.button_dance_picture_6 = QtWidgets.QPushButton(form_dance)
        self.button_dance_picture_6.setGeometry(QtCore.QRect(260, 150, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.button_dance_picture_6.setFont(font)
        self.button_dance_picture_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_dance_picture_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_dance_picture_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(137, 235, 255);\n"
"color: rgb(0, 0, 0);")
        self.button_dance_picture_6.setText("")
        self.button_dance_picture_6.setObjectName("button_dance_picture_6")

        self.retranslateUi(form_dance)
        QtCore.QMetaObject.connectSlotsByName(form_dance)

    def retranslateUi(self, form_dance):
        _translate = QtCore.QCoreApplication.translate
        form_dance.setWindowTitle(_translate("form_dance", "Calibration"))
        self.button_dance_turn_around.setText(_translate("form_dance", "Turn Around"))
        self.button_dance_dancing.setText(_translate("form_dance", "Dancing"))
        self.button_dance_push_up.setText(_translate("form_dance", "Push-Up"))
        self.button_dance_stretch_self.setText(_translate("form_dance", "Stretch self"))
        self.button_dance_say_hello.setText(_translate("form_dance", "Say Hello"))
        self.button_dance_sit_down.setText(_translate("form_dance", "Sit Down"))
