# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_led.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_led(object):
    def setupUi(self, led):
        led.setObjectName("led")
        led.resize(401, 258)
        font = QtGui.QFont()
        font.setFamily("Arial")
        led.setFont(font)
        led.setStyleSheet("QWidget{\n"
"background:#484848;\n"
"}\n"
"QAbstractButton{\n"
"border-style:none;\n"
"border-radius:0px;\n"
"padding:5px;\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #858585,stop:1 #383838);\n"
"}\n"
"QAbstractButton:hover{\n"
"color:#000000;\n"
"background-color:#008aff;\n"
"}\n"
"QAbstractButton:pressed{\n"
"color:#DCDCDC;\n"
"border-style:solid;\n"
"border-width:0px 0px 0px 4px;\n"
"padding:4px 4px 4px 2px;\n"
"border-color:#008aff;\n"
"background-color:#444444;\n"
"}\n"
"\n"
"QLabel{\n"
"color:#DCDCDC;\n"
"\n"
"\n"
"}\n"
"QLabel:focus{\n"
"border:1px solid #00BB9E;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#484848;\n"
"selection-color:#DCDCDC;\n"
"}\n"
"QLineEdit:focus,QLineEdit:hover{\n"
"border:1px solid #242424;\n"
"}\n"
"QLineEdit{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#484848;\n"
"selection-color:#DCDCDC;\n"
"}\n"
"\n"
"QLineEdit:focus,QLineEdit:hover{\n"
"border:1px solid #242424;\n"
"}\n"
"QLineEdit{\n"
"lineedit-password-character:9679;\n"
"}\n"
"font: 10pt \"Arial\";")
        self.widget_led_color_disk = QtWidgets.QWidget(led)
        self.widget_led_color_disk.setGeometry(QtCore.QRect(120, 40, 191, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.widget_led_color_disk.setFont(font)
        self.widget_led_color_disk.setObjectName("widget_led_color_disk")
        self.label_led_4 = QtWidgets.QLabel(led)
        self.label_led_4.setGeometry(QtCore.QRect(325, 220, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_led_4.setFont(font)
        self.label_led_4.setStyleSheet("font: 10pt \"Arial\";")
        self.label_led_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_led_4.setObjectName("label_led_4")
        self.verticalSlider_led_brightness = QtWidgets.QSlider(led)
        self.verticalSlider_led_brightness.setGeometry(QtCore.QRect(350, 50, 22, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.verticalSlider_led_brightness.setFont(font)
        self.verticalSlider_led_brightness.setMaximum(255)
        self.verticalSlider_led_brightness.setProperty("value", 255)
        self.verticalSlider_led_brightness.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_led_brightness.setObjectName("verticalSlider_led_brightness")
        self.verticalLayoutWidget = QtWidgets.QWidget(led)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 91, 208))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_led_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_led_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_led_1.setSpacing(10)
        self.verticalLayout_led_1.setObjectName("verticalLayout_led_1")
        self.checkBox_led_mode_off = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_led_mode_off.setFont(font)
        self.checkBox_led_mode_off.setAcceptDrops(False)
        self.checkBox_led_mode_off.setStyleSheet("font: 10pt \"Arial\";")
        self.checkBox_led_mode_off.setChecked(True)
        self.checkBox_led_mode_off.setObjectName("checkBox_led_mode_off")
        self.verticalLayout_led_1.addWidget(self.checkBox_led_mode_off)
        self.checkBox_led_mode_rgb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_led_mode_rgb.setFont(font)
        self.checkBox_led_mode_rgb.setStyleSheet("font: 10pt \"Arial\";")
        self.checkBox_led_mode_rgb.setObjectName("checkBox_led_mode_rgb")
        self.verticalLayout_led_1.addWidget(self.checkBox_led_mode_rgb)
        self.checkBox_led_mode_following = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_led_mode_following.setFont(font)
        self.checkBox_led_mode_following.setStyleSheet("font: 10pt \"Arial\";")
        self.checkBox_led_mode_following.setObjectName("checkBox_led_mode_following")
        self.verticalLayout_led_1.addWidget(self.checkBox_led_mode_following)
        self.checkBox_led_mode_blink = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_led_mode_blink.setFont(font)
        self.checkBox_led_mode_blink.setStyleSheet("font: 10pt \"Arial\";")
        self.checkBox_led_mode_blink.setObjectName("checkBox_led_mode_blink")
        self.verticalLayout_led_1.addWidget(self.checkBox_led_mode_blink)
        self.checkBox_led_mode_breathing = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_led_mode_breathing.setFont(font)
        self.checkBox_led_mode_breathing.setStyleSheet("font: 10pt \"Arial\";")
        self.checkBox_led_mode_breathing.setObjectName("checkBox_led_mode_breathing")
        self.verticalLayout_led_1.addWidget(self.checkBox_led_mode_breathing)
        self.checkBox_led_mode_rainbow = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_led_mode_rainbow.setFont(font)
        self.checkBox_led_mode_rainbow.setStyleSheet("font: 10pt \"Arial\";")
        self.checkBox_led_mode_rainbow.setObjectName("checkBox_led_mode_rainbow")
        self.verticalLayout_led_1.addWidget(self.checkBox_led_mode_rainbow)
        self.checkBox_led_mode_off.raise_()
        self.checkBox_led_mode_rgb.raise_()
        self.checkBox_led_mode_blink.raise_()
        self.checkBox_led_mode_breathing.raise_()
        self.checkBox_led_mode_rainbow.raise_()
        self.checkBox_led_mode_following.raise_()
        self.lineEdit_led_brightness = QtWidgets.QLineEdit(led)
        self.lineEdit_led_brightness.setGeometry(QtCore.QRect(340, 20, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_led_brightness.setFont(font)
        self.lineEdit_led_brightness.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_led_brightness.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_led_brightness.setObjectName("lineEdit_led_brightness")
        self.label_led_color_disk = QtWidgets.QLabel(led)
        self.label_led_color_disk.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_led_color_disk.setFont(font)
        self.label_led_color_disk.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_led_color_disk.setText("")
        self.label_led_color_disk.setObjectName("label_led_color_disk")
        self.layoutWidget = QtWidgets.QWidget(led)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 20, 188, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_led_update_color = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_led_update_color.setFont(font)
        self.button_led_update_color.setStyleSheet("font: 10pt \"Arial\";")
        self.button_led_update_color.setObjectName("button_led_update_color")
        self.horizontalLayout.addWidget(self.button_led_update_color)
        self.lineEdit_led_color_r = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_led_color_r.setFont(font)
        self.lineEdit_led_color_r.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_led_color_r.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_led_color_r.setObjectName("lineEdit_led_color_r")
        self.horizontalLayout.addWidget(self.lineEdit_led_color_r)
        self.lineEdit_led_color_g = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_led_color_g.setFont(font)
        self.lineEdit_led_color_g.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_led_color_g.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_led_color_g.setObjectName("lineEdit_led_color_g")
        self.horizontalLayout.addWidget(self.lineEdit_led_color_g)
        self.lineEdit_led_color_b = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_led_color_b.setFont(font)
        self.lineEdit_led_color_b.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_led_color_b.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_led_color_b.setObjectName("lineEdit_led_color_b")
        self.horizontalLayout.addWidget(self.lineEdit_led_color_b)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout.setStretch(2, 8)
        self.horizontalLayout.setStretch(3, 8)

        self.retranslateUi(led)
        QtCore.QMetaObject.connectSlotsByName(led)

    def retranslateUi(self, led):
        _translate = QtCore.QCoreApplication.translate
        led.setWindowTitle(_translate("led", "Led"))
        self.label_led_4.setText(_translate("led", "Brightness"))
        self.checkBox_led_mode_off.setText(_translate("led", "OFF"))
        self.checkBox_led_mode_rgb.setText(_translate("led", "RGB"))
        self.checkBox_led_mode_following.setText(_translate("led", "Following"))
        self.checkBox_led_mode_blink.setText(_translate("led", "Blink"))
        self.checkBox_led_mode_breathing.setText(_translate("led", "Breathing"))
        self.checkBox_led_mode_rainbow.setText(_translate("led", "Rainbow"))
        self.lineEdit_led_brightness.setText(_translate("led", "255"))
        self.button_led_update_color.setText(_translate("led", "RGB:"))
        self.lineEdit_led_color_r.setText(_translate("led", "255"))
        self.lineEdit_led_color_g.setText(_translate("led", "255"))
        self.lineEdit_led_color_b.setText(_translate("led", "255"))
