# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_main(object):
    def setupUi(self, form_main):
        form_main.setObjectName("form_main")
        form_main.resize(652, 422)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        form_main.setFont(font)
        form_main.setAutoFillBackground(True)
        form_main.setStyleSheet("font: 10pt \"Arial\";")
        self.label_main_video = QtWidgets.QLabel(form_main)
        self.label_main_video.setGeometry(QtCore.QRect(10, 20, 320, 240))
        self.label_main_video.setStyleSheet("font: 10pt \"Arial\";")
        self.label_main_video.setFrameShape(QtWidgets.QFrame.Box)
        self.label_main_video.setText("")
        self.label_main_video.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_video.setObjectName("label_main_video")
        self.button_main_ccw_90_degree = QtWidgets.QPushButton(form_main)
        self.button_main_ccw_90_degree.setGeometry(QtCore.QRect(10, 280, 101, 31))
        self.button_main_ccw_90_degree.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_ccw_90_degree.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(216, 216, 216);")
        self.button_main_ccw_90_degree.setObjectName("button_main_ccw_90_degree")
        self.button_main_original_degree = QtWidgets.QPushButton(form_main)
        self.button_main_original_degree.setGeometry(QtCore.QRect(120, 280, 101, 31))
        self.button_main_original_degree.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_original_degree.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_original_degree.setObjectName("button_main_original_degree")
        self.button_main_cw_90_degree = QtWidgets.QPushButton(form_main)
        self.button_main_cw_90_degree.setGeometry(QtCore.QRect(230, 280, 101, 31))
        self.button_main_cw_90_degree.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_cw_90_degree.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_cw_90_degree.setObjectName("button_main_cw_90_degree")
        self.button_main_firmware = QtWidgets.QPushButton(form_main)
        self.button_main_firmware.setGeometry(QtCore.QRect(350, 20, 91, 31))
        self.button_main_firmware.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_firmware.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(216, 216, 216);\n"
"")
        self.button_main_firmware.setObjectName("button_main_firmware")
        self.button_main_configure = QtWidgets.QPushButton(form_main)
        self.button_main_configure.setGeometry(QtCore.QRect(450, 20, 91, 31))
        self.button_main_configure.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_configure.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(216, 216, 216);\n"
"")
        self.button_main_configure.setObjectName("button_main_configure")
        self.button_main_led = QtWidgets.QPushButton(form_main)
        self.button_main_led.setGeometry(QtCore.QRect(550, 20, 91, 31))
        self.button_main_led.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_led.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_led.setObjectName("button_main_led")
        self.button_main_calibration = QtWidgets.QPushButton(form_main)
        self.button_main_calibration.setGeometry(QtCore.QRect(450, 60, 91, 31))
        self.button_main_calibration.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_calibration.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_calibration.setObjectName("button_main_calibration")
        self.button_main_action = QtWidgets.QPushButton(form_main)
        self.button_main_action.setGeometry(QtCore.QRect(550, 60, 91, 31))
        self.button_main_action.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_action.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_action.setObjectName("button_main_action")
        self.lineEdit_main_ip_address = QtWidgets.QLineEdit(form_main)
        self.lineEdit_main_ip_address.setGeometry(QtCore.QRect(10, 330, 101, 31))
        self.lineEdit_main_ip_address.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_main_ip_address.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_main_ip_address.setObjectName("lineEdit_main_ip_address")
        self.button_main_connect = QtWidgets.QPushButton(form_main)
        self.button_main_connect.setGeometry(QtCore.QRect(120, 330, 101, 31))
        self.button_main_connect.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_connect.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_connect.setObjectName("button_main_connect")
        self.button_main_video = QtWidgets.QPushButton(form_main)
        self.button_main_video.setGeometry(QtCore.QRect(230, 330, 101, 31))
        self.button_main_video.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_video.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_video.setObjectName("button_main_video")
        self.button_main_twist_mode = QtWidgets.QPushButton(form_main)
        self.button_main_twist_mode.setGeometry(QtCore.QRect(450, 100, 91, 31))
        self.button_main_twist_mode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_twist_mode.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_twist_mode.setObjectName("button_main_twist_mode")
        self.progress_Power_main_percentage = QtWidgets.QProgressBar(form_main)
        self.progress_Power_main_percentage.setGeometry(QtCore.QRect(10, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.progress_Power_main_percentage.setFont(font)
        self.progress_Power_main_percentage.setStyleSheet("QProgressBar {\n"
"border: 2px solid grey;\n"
"border-radius: 5px;\n"
"background-color: #FFFFFF;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: rgb(170, 255, 0);\n"
"width: 5px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"text-align: center; \n"
"color: rgb(0, 85, 255);\n"
"}\n"
"font: 10pt \"Arial\";")
        self.progress_Power_main_percentage.setProperty("value", 0)
        self.progress_Power_main_percentage.setObjectName("progress_Power_main_percentage")
        self.lineEdit_main_sonar_distance = QtWidgets.QLineEdit(form_main)
        self.lineEdit_main_sonar_distance.setGeometry(QtCore.QRect(120, 380, 101, 31))
        self.lineEdit_main_sonar_distance.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_main_sonar_distance.setObjectName("lineEdit_main_sonar_distance")
        self.button_main_sonar_mode = QtWidgets.QPushButton(form_main)
        self.button_main_sonar_mode.setGeometry(QtCore.QRect(550, 100, 91, 31))
        self.button_main_sonar_mode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_sonar_mode.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_sonar_mode.setObjectName("button_main_sonar_mode")
        self.button_main_move_mode = QtWidgets.QPushButton(form_main)
        self.button_main_move_mode.setGeometry(QtCore.QRect(350, 100, 91, 31))
        self.button_main_move_mode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_move_mode.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_move_mode.setCheckable(False)
        self.button_main_move_mode.setChecked(False)
        self.button_main_move_mode.setObjectName("button_main_move_mode")
        self.button_main_buzzer = QtWidgets.QPushButton(form_main)
        self.button_main_buzzer.setGeometry(QtCore.QRect(350, 60, 91, 31))
        self.button_main_buzzer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_buzzer.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_buzzer.setObjectName("button_main_buzzer")
        self.button_main_relax = QtWidgets.QPushButton(form_main)
        self.button_main_relax.setGeometry(QtCore.QRect(230, 380, 101, 31))
        self.button_main_relax.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_relax.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_relax.setObjectName("button_main_relax")
        self.horizontalSlider_main_speed = QtWidgets.QSlider(form_main)
        self.horizontalSlider_main_speed.setGeometry(QtCore.QRect(410, 180, 171, 31))
        self.horizontalSlider_main_speed.setMinimum(1)
        self.horizontalSlider_main_speed.setMaximum(8)
        self.horizontalSlider_main_speed.setPageStep(1)
        self.horizontalSlider_main_speed.setProperty("value", 5)
        self.horizontalSlider_main_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_main_speed.setObjectName("horizontalSlider_main_speed")
        self.label_main_speed = QtWidgets.QLabel(form_main)
        self.label_main_speed.setGeometry(QtCore.QRect(350, 180, 54, 31))
        self.label_main_speed.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.label_main_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_speed.setObjectName("label_main_speed")
        self.lineEdit_main_speed = QtWidgets.QLineEdit(form_main)
        self.lineEdit_main_speed.setGeometry(QtCore.QRect(590, 180, 51, 31))
        self.lineEdit_main_speed.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_main_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_main_speed.setObjectName("lineEdit_main_speed")
        self.lineEdit_main_step = QtWidgets.QLineEdit(form_main)
        self.lineEdit_main_step.setGeometry(QtCore.QRect(590, 140, 51, 31))
        self.lineEdit_main_step.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_main_step.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_main_step.setObjectName("lineEdit_main_step")
        self.horizontalSlider_main_step = QtWidgets.QSlider(form_main)
        self.horizontalSlider_main_step.setGeometry(QtCore.QRect(410, 140, 171, 31))
        self.horizontalSlider_main_step.setMinimum(1)
        self.horizontalSlider_main_step.setMaximum(40)
        self.horizontalSlider_main_step.setPageStep(5)
        self.horizontalSlider_main_step.setProperty("value", 20)
        self.horizontalSlider_main_step.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_main_step.setObjectName("horizontalSlider_main_step")
        self.label_main_step = QtWidgets.QLabel(form_main)
        self.label_main_step.setGeometry(QtCore.QRect(350, 140, 54, 31))
        self.label_main_step.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.label_main_step.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_step.setObjectName("label_main_step")
        self.button_main_forward = QtWidgets.QPushButton(form_main)
        self.button_main_forward.setGeometry(QtCore.QRect(440, 260, 101, 31))
        self.button_main_forward.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.button_main_forward.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(216, 216, 216);\n"
"")
        self.button_main_forward.setObjectName("button_main_forward")
        self.button_main_left_shift = QtWidgets.QPushButton(form_main)
        self.button_main_left_shift.setGeometry(QtCore.QRect(380, 340, 101, 31))
        self.button_main_left_shift.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_left_shift.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_left_shift.setObjectName("button_main_left_shift")
        self.button_main_backward = QtWidgets.QPushButton(form_main)
        self.button_main_backward.setGeometry(QtCore.QRect(440, 380, 101, 31))
        self.button_main_backward.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_backward.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(216, 216, 216);\n"
"")
        self.button_main_backward.setObjectName("button_main_backward")
        self.button_main_right_shift = QtWidgets.QPushButton(form_main)
        self.button_main_right_shift.setGeometry(QtCore.QRect(500, 340, 101, 31))
        self.button_main_right_shift.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_right_shift.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_right_shift.setObjectName("button_main_right_shift")
        self.button_main_turn_left = QtWidgets.QPushButton(form_main)
        self.button_main_turn_left.setGeometry(QtCore.QRect(380, 300, 101, 31))
        self.button_main_turn_left.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_turn_left.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_turn_left.setObjectName("button_main_turn_left")
        self.button_main_turn_right = QtWidgets.QPushButton(form_main)
        self.button_main_turn_right.setGeometry(QtCore.QRect(500, 300, 101, 31))
        self.button_main_turn_right.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_main_turn_right.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.button_main_turn_right.setObjectName("button_main_turn_right")
        self.horizontalSlider_main_gama = QtWidgets.QSlider(form_main)
        self.horizontalSlider_main_gama.setGeometry(QtCore.QRect(410, 220, 171, 31))
        self.horizontalSlider_main_gama.setMinimum(0)
        self.horizontalSlider_main_gama.setMaximum(20)
        self.horizontalSlider_main_gama.setPageStep(5)
        self.horizontalSlider_main_gama.setProperty("value", 5)
        self.horizontalSlider_main_gama.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_main_gama.setObjectName("horizontalSlider_main_gama")
        self.lineEdit_main_gama = QtWidgets.QLineEdit(form_main)
        self.lineEdit_main_gama.setGeometry(QtCore.QRect(590, 220, 51, 31))
        self.lineEdit_main_gama.setStyleSheet("font: 10pt \"Arial\";")
        self.lineEdit_main_gama.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_main_gama.setObjectName("lineEdit_main_gama")
        self.label_main_gama = QtWidgets.QLabel(form_main)
        self.label_main_gama.setGeometry(QtCore.QRect(350, 220, 54, 31))
        self.label_main_gama.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 10pt \"Arial\";")
        self.label_main_gama.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_gama.setObjectName("label_main_gama")

        self.retranslateUi(form_main)
        QtCore.QMetaObject.connectSlotsByName(form_main)

    def retranslateUi(self, form_main):
        _translate = QtCore.QCoreApplication.translate
        form_main.setWindowTitle(_translate("form_main", "Freenove"))
        self.button_main_ccw_90_degree.setText(_translate("form_main", "CCW-90°"))
        self.button_main_original_degree.setText(_translate("form_main", "Original"))
        self.button_main_cw_90_degree.setText(_translate("form_main", "CW-90°"))
        self.button_main_firmware.setText(_translate("form_main", "Firmware"))
        self.button_main_configure.setText(_translate("form_main", "Configure"))
        self.button_main_led.setText(_translate("form_main", "LED"))
        self.button_main_calibration.setText(_translate("form_main", "Calibration"))
        self.button_main_action.setText(_translate("form_main", "Action"))
        self.lineEdit_main_ip_address.setText(_translate("form_main", "IP Address"))
        self.button_main_connect.setText(_translate("form_main", "Connect"))
        self.button_main_video.setText(_translate("form_main", "Open video"))
        self.button_main_twist_mode.setText(_translate("form_main", "Twist"))
        self.lineEdit_main_sonar_distance.setText(_translate("form_main", "Distance"))
        self.button_main_sonar_mode.setText(_translate("form_main", "Sonar"))
        self.button_main_move_mode.setText(_translate("form_main", "Move"))
        self.button_main_buzzer.setText(_translate("form_main", "Buzzer"))
        self.button_main_relax.setText(_translate("form_main", "Relax"))
        self.label_main_speed.setText(_translate("form_main", "Speed:"))
        self.lineEdit_main_speed.setText(_translate("form_main", "5"))
        self.lineEdit_main_step.setText(_translate("form_main", "20"))
        self.label_main_step.setText(_translate("form_main", "Step:"))
        self.button_main_forward.setText(_translate("form_main", "ForWard"))
        self.button_main_left_shift.setText(_translate("form_main", "Left Shift"))
        self.button_main_backward.setText(_translate("form_main", "BackWard"))
        self.button_main_right_shift.setText(_translate("form_main", "Right Shift"))
        self.button_main_turn_left.setText(_translate("form_main", "Turn Left"))
        self.button_main_turn_right.setText(_translate("form_main", "Turn Right"))
        self.lineEdit_main_gama.setText(_translate("form_main", "5"))
        self.label_main_gama.setText(_translate("form_main", "Gama"))
